name: valorantinfo
description: A simple valorant info app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^2.7.94
  flutter_launcher_icons: ^0.7.4
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - img/valorant.png
  - img/valorant.jpg
  - img/breach.jpg
  - img/viper.jpg
  - img/omen.jpg
  - img/jett.jpg
  - img/sage.jpg
  - img/sova.jpg
  - img/phoenix.jpg
  - img/cypher.jpg
  - img/brimstone.jpg
  - img/raze.jpg


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "icons/valorant.jpg"